name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start API (background)
        run: |
          nohup python -m uvicorn app.api:app --host 127.0.0.1 --port 8000 >/dev/null 2>&1 &
          for i in {1..40}; do curl -fsS http://127.0.0.1:8000/docs && break || sleep 1; done

      - name: Unit tests
        run: pytest tests/unit -q

      - name: Integration tests
        run: pytest tests/integration -q

      - name: API tests
        run: pytest tests/api -q

      - name: Smoke tests
        run: pytest -m smoke -q

      - name: JUnit report
        if: always()
        run: pytest -q --junitxml=report.xml
